### ISSUE TITLE
[Question] Use with Handlebars static methods?

### ISSUE THREAD

**Issue by winzig** [Handlebars-Net/Handlebars.Net.Extension.NewtonsoftJson#1]
It's entirely possible I was using Handlebars.net incorrectly, but my code is not currently using Handlebars.Create to create a new instance, instead using `Handlebars.Compile` static method directly. 

Should I switch to creating an instance with this configuration for Newtonsoft, or is there a path forward with the existing static method use?

**Comment by oformaniuk** [comment]
Hello @winzig 
You can definitely continue using static approach:
`Handlebars.Configuration.UseNewtonsoftJson()`.
However you should add this line before you do any compilation.
